disabled_rules:
    - trailing_whitespace
opt_in_rules:
    - empty_count
excluded:
    - Carthage
    - Pods
analyzer_rules:
    - explicit_self
force_cast: warning
force_try:
    severity: warning
line_length: 172
type_body_length:
    - 300
    - 400
file_length:
    warning: 500
    error: 1200
nesting:
    type_level:
        warning: 5
        error: 6
type_name:
    min_length: 4
    max_length:
        warning: 50
        error: 60
    excluded: iPhone
    allowed_symbols: ["_"]
identifier_name:
    min_length: 2
    error: 1
    excluded:
    - id
    - URL
    - GlobalAPIKey
reporter: "xcode"
